name: "PR review"
on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited, edited]

jobs:
  labeler:
    name: review
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    # Welcome comment
    - name: "First timers PR"
      uses: actions/first-interaction@v1
      if: github.event.pull_request.head.repo.full_name != 'commaai/openpilot'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: |
            <!-- _(run_id **${{ github.run_id }}**)_ -->
            Thanks for contributing to openpilot! In order for us to review your PR as quickly as possible, check the following:
            * Convert your PR to a draft unless it's ready to review
            * Read the [contributing docs](https://github.com/commaai/openpilot/blob/master/docs/CONTRIBUTING.md)
            * Before marking as "ready for review", ensure:
              * the goal is clearly stated in the description
              * all the tests are passing
              * the change is [something we merge](https://github.com/commaai/openpilot/blob/master/docs/CONTRIBUTING.md#what-gets-merged)
              * include a route or your device' dongle ID if relevant
      
